[package]
name = "cch23-razzdrgn"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.34.0"
tokio = "1"
axum = { version = "0.7", features = ["tokio", "http2"] }
tracing = "0.1"
tower-http = { version = "0.5", features = ["trace"] }
serde = "1.0"
serde_json = "1.0"

[lints.clippy]
pedantic = { level = "warn" }
cargo = { level = "warn" }